In [20]:
import matplotlib.pyplot as plt
import math
import numpy as np
import random

import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms

import torchvision
import os


EPSILON = 1.5 * 10**-12
LAMBDA = 0.0001
LEARNING_RATE = 0.0001
BATCH_SIZE = 100
FEATURE_SIZE = 10000




In [21]:
### Setting up Device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# Below codes activates when want to use cpu
device = torch.device('cpu')
print('Using device:', device)
print()

#Additional Info when using cuda
if device.type == 'cuda':
    print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_cached(0)/1024**3,1), 'GB')

Using device: cpu



In [28]:
class Test :
    def __init__(self,L1_size,L2_size,L3_size) :
        self.l1_size =L1_size
        self.l2_size = L2_size
        self.l3_size = L3_size
        self.feature_size = 10000
        self.init_weights()
    def init_weights(self) :
        # w_1 size is falut
            self.w_1 = torch.FloatTensor(self.l1_size,self.feature_size).uniform_(-1,1).to(device)

            self.b_1 = torch.FloatTensor(1,self.l1_size).uniform_(-1,1).to(device)

            #torch.FloatTensor(a, b).uniform_(r1, r2)

            self.w_2 = torch.FloatTensor(self.l2_size,self.l1_size).uniform_(-1,1).to(device)
            self.b_2 = torch.FloatTensor(1,self.l2_size).uniform_(-1,1).to(device)

            self.w_3 = torch.FloatTensor(self.l3_size,self.l2_size).uniform_(-1,1).to(device)
            self.b_3 = torch.FloatTensor(1,self.l3_size).uniform_(-1,1).to(device)

            self.batch_size = 100
            self.input_sample = torch.FloatTensor(batch_size,10000).uniform_(-1,1).to(device)
            
            
    def main(self) :
        print("w_1 shape : ",self.w_1.shape)
        print("input shape : ",self.input_sample.shape)

In [72]:
L1_size = 10
L2_size = 5
L3_size = 1
batch_size = 100

#test = Test(10,5,1)
#test.main()
w_1 = torch.FloatTensor(10000,10).uniform_(-1,1)
input_sample = torch.ones(100,10000).uniform_(-1,1)
b_1 = torch.FloatTensor(1,10).uniform_(-1,1)
z_1 = torch.matmul(input_sample,w_1) + b_1


w_2 = torch.ones(10,5)
z_2 = torch.matmul(z_1,w_2)

w_3 = torch.ones(5,1)
z_3 = torch.matmul(z_2,w_3)


print("z_1 shape : ", z_1.shape)
print("z_2 shape : ", z_2.shape)
print("z_3 shape : ", z_3.shape)
print(b_1)
print(z_1)

z_1 shape :  torch.Size([100, 10])
z_2 shape :  torch.Size([100, 5])
z_3 shape :  torch.Size([100, 1])
tensor([[ 0.9566, -0.4143,  0.1013, -0.2230,  0.3798,  0.6138, -0.0127,  0.5909,
          0.7356, -0.2437]])
tensor([[-8.2370e+00, -4.0939e+01,  9.7335e+00, -1.3669e+01,  7.7909e+00,
         -3.4455e+00,  1.6362e-01,  1.9650e+01, -5.9629e+00, -3.4620e+01],
        [ 1.2286e+01,  4.5518e+01,  1.0248e+01,  5.4889e+00, -2.6617e+01,
         -4.4392e+01, -3.2097e+00, -6.7989e+01,  2.4822e+01,  4.4346e+01],
        [-1.6790e+01, -3.5256e+01,  5.7514e+01,  7.2658e+00,  3.2658e-01,
          2.4315e+00,  2.0636e+01, -4.7451e+01,  2.7448e+01, -2.6551e+01],
        [ 3.0466e+01,  6.1866e+01, -3.9586e+01,  4.4870e+01,  1.4813e+01,
         -2.6882e+00,  4.4305e+01,  5.6486e+01,  1.1800e+01, -2.7269e+01],
        [-1.9923e+01,  1.8368e+01,  1.8714e+01, -8.5301e+00, -2.3158e+01,
         -8.1960e+00, -1.9574e+01,  1.4837e+01,  5.4392e+01, -5.5757e+00],
        [-2.6890e+01, -2.9803e+01,  3.9803

In [74]:

test = torch.FloatTensor(3,3).uniform_(-1,1)
print(test)
test = test**2
print(test)







tensor([[ 0.8583,  0.6271, -0.7347],
        [-0.7403, -0.3686, -0.3934],
        [-0.6039, -0.3850, -0.8710]])
tensor([[0.7366, 0.3932, 0.5398],
        [0.5480, 0.1358, 0.1547],
        [0.3647, 0.1482, 0.7586]])
